@extends('frontend.layouts.app')

@section('styles')
<style>
	body:has(.ug-home) .header-top, body:has(.ug-home) .header-sticky, body:has(.ug-home) .offcanvas { display: none; }
	.ug-home { --ink: #14231f; --muted: #60716a; --green: #147d55; --lime: #d7f36b; --cream: #f7f5ee; --line: #dce5df; color: var(--ink); background: var(--cream); overflow: hidden; }
	body:has(.ug-home) #preloader { display: none !important; }
	.ug-home .container { max-width: 1180px; }
	.ug-nav { position: relative; z-index: 2; display: flex; align-items: center; justify-content: space-between; padding: 22px 0; }
	.ug-brand { color: var(--ink); font-size: 21px; font-weight: 900; letter-spacing: 1px; text-decoration: none; }
	.ug-brand span { color: var(--green); }
	.ug-nav-links { display: flex; align-items: center; gap: 28px; }
	.ug-nav-links a { color: var(--ink); font-size: 13px; font-weight: 700; text-decoration: none; }
	.ug-nav-links .ug-nav-cta { min-height: 40px; padding: 0 17px; color: #fff; background: var(--green); border-radius: 4px; }
	.ug-hero { padding: 92px 0 72px; background: radial-gradient(circle at 82% 12%, #e1f2c5 0, transparent 28%), linear-gradient(135deg, #f7f5ee 0%, #eef6e9 100%); }
	.ug-kicker { display: inline-flex; align-items: center; gap: 9px; color: var(--green); font-size: 12px; font-weight: 800; letter-spacing: 1.3px; text-transform: uppercase; }
	.ug-kicker:before { content: ''; width: 24px; height: 3px; background: var(--green); border-radius: 2px; }
	.ug-hero h1 { max-width: 650px; margin: 18px 0; font-size: clamp(44px, 6vw, 76px); line-height: .98; letter-spacing: -2px; font-weight: 800; }
	.ug-hero h1 span { color: var(--green); }
	.ug-lead { max-width: 565px; color: var(--muted); font-size: 18px; line-height: 1.65; }
	.ug-actions { display: flex; flex-wrap: wrap; gap: 13px; margin-top: 28px; }
	.ug-btn { display: inline-flex; align-items: center; justify-content: center; min-height: 50px; padding: 0 22px; border-radius: 5px; font-weight: 750; text-decoration: none; transition: transform .2s ease, box-shadow .2s ease; }
	.ug-btn:hover { transform: translateY(-2px); box-shadow: 0 10px 22px rgba(20, 125, 85, .14); }
	.ug-btn-primary { color: #fff; background: var(--green); }
	.ug-btn-light { color: var(--ink); border: 1px solid var(--line); background: #fff; }
	.ug-proof { display: flex; flex-wrap: wrap; gap: 25px; margin-top: 34px; color: var(--muted); font-size: 13px; }
	.ug-proof strong { display: block; color: var(--ink); font-size: 18px; }
	.ug-hero-art { position: relative; min-height: 420px; }
	.ug-phone { position: absolute; right: 9%; top: 16px; width: min(310px, 78%); padding: 18px; border: 8px solid #172b25; border-radius: 28px; background: #fff; box-shadow: 25px 25px 0 #cce7be; transform: rotate(4deg); }
	.ug-phone-top { display: flex; justify-content: space-between; color: var(--muted); font-size: 11px; }
	.ug-phone-top span:first-child { font-size: 0; }
	.ug-phone-top span:first-child:after { content: 'REEXPAY wallet'; font-size: 11px; }
	.ug-balance { margin: 21px 0; padding: 22px; border-radius: 12px; color: #fff; background: var(--green); }
	.ug-balance small { opacity: .75; } .ug-balance strong { display: block; margin-top: 8px; font-size: 27px; }
	.ug-phone-row { display: flex; justify-content: space-between; padding: 14px 0; border-bottom: 1px solid #edf1ed; font-size: 12px; } .ug-phone-row b { color: var(--green); }
	.ug-float { position: absolute; left: 0; bottom: 30px; padding: 15px 18px; border-radius: 9px; background: #fff; box-shadow: 0 14px 35px rgba(20, 53, 39, .12); font-size: 13px; } .ug-float b { color: var(--green); }
	.ug-rail { padding: 20px 0; border-top: 1px solid var(--line); border-bottom: 1px solid var(--line); background: #fff; } .ug-rail p { margin: 0; color: var(--muted); font-size: 13px; } .ug-rail strong { color: var(--ink); }
	.ug-section { padding: 90px 0; } .ug-section.alt { background: #fff; }
	.ug-section h2 { max-width: 580px; margin: 10px 0 15px; font-size: clamp(32px, 4vw, 52px); line-height: 1.05; letter-spacing: -1px; }
	.ug-section-intro { max-width: 580px; color: var(--muted); line-height: 1.7; }
	.ug-pricing { display: grid; grid-template-columns: 1.1fr .9fr; gap: 18px; margin-top: 42px; }
	.ug-pricing-main, .ug-pricing-note { padding: 30px; border: 1px solid var(--line); border-radius: 8px; }
	.ug-pricing-main { color: #fff; background: var(--green); } .ug-pricing-main strong { display: block; margin-bottom: 8px; color: var(--lime); font-size: 56px; line-height: 1; } .ug-pricing-main p, .ug-pricing-note p { margin: 0; line-height: 1.65; } .ug-pricing-main p { color: #e3f2e9; } .ug-pricing-note { background: var(--cream); } .ug-pricing-note strong { display: block; margin-bottom: 8px; font-size: 18px; }
	.ug-leadership { display: grid; grid-template-columns: repeat(2, 1fr); gap: 16px; margin-top: 38px; } .ug-person { padding: 24px; border-left: 3px solid var(--lime); background: #213b31; } .ug-person strong { display: block; color: #fff; font-size: 20px; } .ug-person span { display: block; margin-top: 6px; color: var(--lime); font-size: 12px; font-weight: 800; letter-spacing: 1px; text-transform: uppercase; } .ug-person p { margin: 14px 0 0; color: #d7e5dd; font-size: 14px; line-height: 1.6; }
	.ug-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-top: 42px; }
	.ug-card { min-height: 218px; padding: 26px; border: 1px solid var(--line); border-radius: 8px; background: #fff; } .alt .ug-card { background: var(--cream); }
	.ug-icon { display: grid; place-items: center; width: 42px; height: 42px; margin-bottom: 25px; border-radius: 50%; color: var(--green); background: var(--lime); font-weight: 900; }
	.ug-card h3 { margin-bottom: 9px; font-size: 20px; } .ug-card p { margin: 0; color: var(--muted); line-height: 1.6; font-size: 14px; }
	.ug-band { padding: 66px 0; color: #fff; background: var(--green); } .ug-band h2 { margin: 0; font-size: 42px; } .ug-band p { max-width: 540px; margin: 14px 0 0; color: #d7eee2; line-height: 1.7; } .ug-band .ug-btn { background: var(--lime); color: var(--ink); }
	.ug-trust { padding: 75px 0; background: #172b25; color: #fff; } .ug-trust h2 { max-width: 530px; margin: 10px 0 15px; color: #fff; font-size: 42px; } .ug-trust .ug-section-intro { color: #c5d8ce; } .ug-trust .ug-kicker { color: var(--lime); } .ug-trust .ug-kicker:before { background: var(--lime); } .ug-trust-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 14px; margin-top: 34px; } .ug-trust-item { padding: 22px; border: 1px solid rgba(255,255,255,.16); border-radius: 7px; } .ug-trust-item strong { display: block; margin-bottom: 8px; color: var(--lime); font-size: 18px; } .ug-trust-item span { color: #d7e5dd; font-size: 13px; line-height: 1.5; }
	.ug-steps { display: grid; grid-template-columns: repeat(3, 1fr); gap: 30px; margin-top: 42px; } .ug-step { padding-top: 18px; border-top: 2px solid var(--green); } .ug-step b { color: var(--green); font-size: 13px; } .ug-step h3 { margin: 12px 0 8px; } .ug-step p { color: var(--muted); line-height: 1.6; font-size: 14px; }
	@media (max-width: 767px) { .ug-hero { padding: 58px 0 45px; } .ug-hero h1 { letter-spacing: -1px; } .ug-hero-art { min-height: 350px; margin-top: 30px; } .ug-phone { right: 3%; } .ug-grid, .ug-steps, .ug-pricing, .ug-leadership { grid-template-columns: 1fr; } .ug-section { padding: 60px 0; } .ug-band h2 { font-size: 34px; } }
	@media (max-width: 767px) { .ug-trust { padding: 60px 0; } .ug-trust h2 { font-size: 34px; } .ug-trust-grid { grid-template-columns: 1fr; } }
</style>
@endsection

@section('content')
<main class="ug-home">
	<section class="ug-hero">
		<div class="container"><nav class="ug-nav"><a class="ug-brand" href="{{ route('home') }}">REEXPAY</a><div class="ug-nav-links"><a href="#solutions">Solutions</a><a href="{{ route('api-docs.index') }}">Developers</a><a href="{{ route('user.login') }}">Sign in</a><a class="ug-nav-cta" href="{{ route('user.register') }}">Get started</a></div></nav><div class="row align-items-center g-5">
			<div class="col-lg-7">
				<span class="ug-kicker">Made for Uganda</span>
				<h1>Move money at the <span>speed of business.</span></h1>
				<p class="ug-lead">A practical digital wallet for Ugandan people and businesses. Collect with MTN and Airtel, pay bills, send funds, and stay in control from one simple account.</p>
				<div class="ug-actions"><a class="ug-btn ug-btn-primary" href="{{ route('user.register') }}">Open your wallet</a><a class="ug-btn ug-btn-light" href="{{ route('user.login') }}">Sign in</a></div>
				<div class="ug-proof"><div><strong>UGX</strong>Local currency first</div><div><strong>MTN + Airtel</strong>Mobile money ready</div><div><strong>24/7</strong>Always-on access</div></div>
			</div>
			<div class="col-lg-5"><div class="ug-hero-art"><div class="ug-phone"><div class="ug-phone-top"><span>REEXPAY wallet</span><span>•••</span></div><div class="ug-balance"><small>Available balance</small><strong>UGX 2,480,000</strong><small>Updated just now</small></div><div class="ug-phone-row"><span>MTN collection</span><b>+ UGX 180,000</b></div><div class="ug-phone-row"><span>UMEME bill</span><b>- UGX 64,500</b></div><div class="ug-phone-row"><span>Bank payout</span><b>- UGX 420,000</b></div></div><div class="ug-float"><b>Payment received</b><br>MTN Mobile Money · UGX 180,000</div></div></div>
		</div></div>
	</section>
	<div class="ug-rail"><div class="container"><div class="row gy-3"><div class="col-md-3"><p><strong>One local wallet</strong><br>For everyday Ugandan money</p></div><div class="col-md-3"><p><strong>Mobile money</strong><br>MTN and Airtel collections</p></div><div class="col-md-3"><p><strong>Bank payouts</strong><br>Send money when it matters</p></div><div class="col-md-3"><p><strong>Built for teams</strong><br>Simple controls and records</p></div></div></div></div>
	<section class="ug-section" id="solutions"><div class="container"><span class="ug-kicker">One platform</span><h2>Everything you need to move money in Uganda.</h2><p class="ug-section-intro">REEXPAY brings everyday wallet tools and business payments into one clear UGX experience, built for people, merchants, and growing teams.</p><div class="ug-grid"><article class="ug-card"><div class="ug-icon">01</div><h3>Collect payments</h3><p>Receive customer payments through local mobile money and keep every transaction visible.</p></article><article class="ug-card"><div class="ug-icon">02</div><h3>Send and withdraw</h3><p>Move funds to a Ugandan mobile-money account with a simple, trackable payout experience.</p></article><article class="ug-card"><div class="ug-icon">03</div><h3>One UGX wallet</h3><p>Manage your balance, payment activity, and records in Uganda's local currency.</p></article><article class="ug-card"><div class="ug-icon">04</div><h3>Business checkout</h3><p>Give customers a straightforward way to pay while your team follows the ledger.</p></article><article class="ug-card"><div class="ug-icon">05</div><h3>Clear records</h3><p>Review deposits, withdrawals, transfers, and merchant payments from one account history.</p></article><article class="ug-card"><div class="ug-icon">06</div><h3>Built for integration</h3><p>Connect your product with documented APIs and webhook notifications when you are ready.</p></article></div></div></section>
	<section class="ug-section alt"><div class="container"><span class="ug-kicker">Simple pricing</span><h2>Keep more of every payment.</h2><p class="ug-section-intro">We believe payment infrastructure should be easy to understand. REEXPAY keeps charges low and makes the cost visible before money moves.</p><div class="ug-pricing"><div class="ug-pricing-main"><strong>3%</strong><p>Our advertised standard charge for eligible payment services. The final amount depends on the service and the transaction details shown in your account.</p></div><div class="ug-pricing-note"><strong>Transparent by design</strong><p>No confusing tiers in the message you see here. Your applicable charge is shown in the payment flow before you confirm.</p></div></div></div></section>
	<section class="ug-section"><div class="container"><span class="ug-kicker">Referral rewards</span><h2>Invite people. Earn from their first activity.</h2><p class="ug-section-intro">Every REEXPAY user has a unique referral link. When someone joins through your link and completes their first eligible transaction, you can earn a referral commission according to the active reward plan.</p><div class="ug-grid"><article class="ug-card"><div class="ug-icon">01</div><h3>Share your link</h3><p>Invite friends, customers, or business contacts using your personal referral link.</p></article><article class="ug-card"><div class="ug-icon">02</div><h3>Earn on first activity</h3><p>Rewards are based on the referred user's first eligible deposit or qualifying transaction.</p></article><article class="ug-card"><div class="ug-icon">03</div><h3>Grow through levels</h3><p>The current reward plan supports level-based commissions of 10% at level one, 5% at level two, and 2% at level three when enabled for the relevant transaction type.</p></article></div><p class="ug-section-intro mt-4">Referral rewards are credited to the referrer's UGX wallet after the qualifying transaction completes. Self-referrals, duplicate accounts, automated signups, and misleading promotion are not eligible.</p></div></section>
	<section class="ug-trust"><div class="container"><span class="ug-kicker">Payments you can see</span><h2>Designed for confident money movement.</h2><p class="ug-section-intro">Every important action has a clear home: secure access, visible balances, and a transaction history you can follow.</p><div class="ug-trust-grid"><div class="ug-trust-item"><strong>UGX ready</strong><span>Work in Uganda's local currency with wallet balances and clear payable amounts.</span></div><div class="ug-trust-item"><strong>2FA and KYC</strong><span>Account verification and two-factor security support safer access to your wallet.</span></div><div class="ug-trust-item"><strong>Live ledger</strong><span>Review deposits, withdrawals, transfers, and merchant payments from your records.</span></div></div></div></section>
	<section class="ug-trust"><div class="container"><span class="ug-kicker">People behind REEXPAY</span><h2>Local focus, ambitious backing.</h2><p class="ug-section-intro">REEXPAY is being shaped around the needs of Ugandan customers and businesses, with leadership and investment focused on building dependable financial access.</p><div class="ug-leadership"><div class="ug-person"><strong>Steve Checkers</strong><span>Founder</span><p>Leading the REEXPAY vision and the work to make everyday money movement simpler for Uganda.</p></div><div class="ug-person"><strong>Kits Lovable Blaise</strong><span>Investor</span><p>Supporting the long-term growth of a practical, locally focused financial platform.</p></div></div></div></section>
	<section class="ug-band"><div class="container"><div class="row align-items-center gy-4"><div class="col-lg-7"><h2>Built around how Uganda pays.</h2><p>Start with a wallet that speaks UGX, supports local payment habits, and gives your business a clean path from first collection to reliable payout.</p></div><div class="col-lg-5 text-lg-end"><a class="ug-btn" href="{{ route('user.merchant.create') }}">Create a merchant account</a></div></div></div></section>
	<section class="ug-section alt"><div class="container"><span class="ug-kicker">Start simply</span><h2>From signup to your first payment.</h2><div class="ug-steps"><div class="ug-step"><b>01 / CREATE</b><h3>Open an account</h3><p>Register with your details and set up your secure REEXPAY profile.</p></div><div class="ug-step"><b>02 / CONNECT</b><h3>Use your UGX wallet</h3><p>Start with one Uganda-focused wallet and the payment tools built around it.</p></div><div class="ug-step"><b>03 / MOVE</b><h3>Send, collect, and grow</h3><p>Start transacting, watch your ledger, and keep your money moving with clarity.</p></div></div><div class="ug-actions"><a class="ug-btn ug-btn-primary" href="{{ route('user.register') }}">Get started today</a><a class="ug-btn ug-btn-light" href="{{ route('api-docs.index') }}">Explore the API docs</a></div></div></section>
</main>
@endsection
